[tool.poetry]
name = "hcaptcha-verifier"
version = "0.1.0"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.80.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
prettyconf = "^2.2.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pylint = "^2.13.9"
pre-commit = "^2.20.0"
isort = "^5.10.1"
pyclean = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
